{% set name = 'pcgr' %}
{% set version = os.environ.get('VERSION', '').replace('v.', '').replace('v', '') or '0.0.1' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../../

build:
  number: 0
  rpaths:
    - lib/
    - lib/R/library/

requirements:
  build:
    - curl
    - unzip
    - tar
    - python =3.7
    - r-base =4.0.2
    - toml
    #
    # Need R packages build-time to correctly install pcgrr
    - bioconductor-biocinstaller
    - r-devtools
    - r-purrr
    - r-dplyr
    - r-stringr
    - r-tidyr
    - r-httr
    - r-git2r
    - r-data.table
    - r-magrittr
    - r-htmltools
    - r-caret
    - r-randomforest
    - r-plotly
    - r-rcpptoml
    - r-ggplot2
    - r-dt
    - r-stringi
    - r-htmlwidgets
    - r-crosstalk
    - r-deconstructsigs
    - r-knitr
    - r-rmarkdown
    - r-configr           # for pcgrr, -c pcgr
    - r-summarywidget     # for pcgrr, -c pcgr
    - r-rlogging          # for pcgrr, -c pcgr
    - r-collapsibletree   # for CELLector
    - r-sunburstr         # for CELLector, -c pcgr
    - r-arules            # for CELLector, on conda-forge now
    - r-biocmanager
    - bioconductor-variantannotation
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-bsgenome.hsapiens.ucsc.hg38
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-regioner
    - bioconductor-mutationalpatterns
    - r-shiny

  run:
    #
    # PCGR: python
    - python =3.7
    - r-base =4.0.2
    - pip
    - numpy
    - cython
    - scipy
    - pandas
    - cyvcf2
    - toml
    - gdown  # google drive CLI to download test data
    #
    # PCGR: other tools
    - tabix
    - samtools
    - bedtools
    - vcfanno
    - vt
    - htslib
    - vcf2maf
    - nlopt
    #
    # Perl (for VEP)
    - perl-bioperl
    - ensembl-vep ==98.3
    #- perl-bio-bigfile  # for Loftee (doesn't come with ensemble-vep, but will come with https://github.com/bioconda/bioconda-recipes/pull/18808 once merged)
    #
    # PCGR: R packages
    - bioconductor-biocinstaller
    - r-devtools
    - r-purrr
    - r-dplyr
    - r-stringr
    - r-tidyr
    - r-httr
    - r-git2r
    - r-data.table
    - r-magrittr
    - r-htmltools
    - r-caret
    - r-randomforest
    - r-plotly
    - r-rcpptoml
    - r-ggplot2
    - r-dt
    - r-stringi
    - r-htmlwidgets
    - r-crosstalk
    - r-deconstructsigs
    - r-knitr
    - r-rmarkdown
    - r-configr           # for pcgrr, -c pcgr
    - r-summarywidget     # for pcgrr, -c pcgr
    - r-rlogging          # for pcgrr, -c pcgr
    - r-collapsibletree   # for CELLector
    - r-sunburstr         # for CELLector, -c pcgr
    - r-arules            # for CELLector
    - r-biocmanager
    - bioconductor-variantannotation
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-bsgenome.hsapiens.ucsc.hg38
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges  # GenomicRangesS4Vectors
    - bioconductor-regioner
    - bioconductor-mutationalpatterns
    - r-shiny

test:
  commands:
    - pcgr.py --version
    - '$R -e "library(pcgrr)"'
    - '$R -e "library(pcgrr) ; pcgrr::acmg_evidence_codes"'
    - '$R -e "library(crosstalk); sessionInfo();"'
  imports:
    - annoutils

about:
  home: https://github.com/sigven/pcgr
  license: MIT
  summary: Personal Cancer Genome Reporter (PCGR)- variant interpretation report for precision oncology

